### PR TITLE
fix(ci): fix clippy warnings for integration tests

### LINKED ISSUE #4006: Some integration tests fail to build
Running `cargo check --tests --features docker` results in a number of errors:

```
    Checking vector v0.11.0 (/home/bruce/Timber/vector)
error[E0599]: no method named `compat` found for struct `std::pin::Pin<std::boxed::Box<dyn core::future::future::Future<Output = std::result::Result<(), std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>>> + std::marker::Send>>` in the current scope
   --> src/sinks/gcp/pubsub.rs:256:21
    |
256 |           healthcheck.compat().await.expect("Health check failed");
    |                       ^^^^^^ method not found in `std::pin::Pin<std::boxed::Box<dyn core::future::future::Future<Output = std::result::Result<(), std::boxed::Box<dyn std::error::Error + std::marker::Send + std::marker::Sync>>> + std::marker::Send>>`
    | 
   ::: /home/bruce/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/mod.rs:571:8
```

`git bisect` indicates the failures were caused by 2272cca0f15812982d81e88ea516850ca45707e6 (#3685).

### PR DESCRIPTION
**Pull request by fanatid**
Closes #4006

### CODE REVIEW

**Comment by fanatid** [comment]
@bruceg I cherry-picked code from #4008 locally and confirmed that `make check-clippy` is ok.

**Review by bruceg — APPROVED** [review]
